### ISSUE TITLE
Multiple CSS Selectors

### ISSUE THREAD

**Issue by cyouh95** [MikeSang/colmar#4]
Alternatively, you could use comma-separated selectors to specify shared properties for multiple elements:

```css
h3, h4, h5, h6 {
  padding-bottom: 12px;
}
```

https://github.com/MikeSang/colmar/blob/master/resources/css/style.css#L53-L77
